#!/usr/bin/env bash
#
# Setup all agent environments
# Note: Keys are auto-generated by the SDK when agents start (dev_mode=True)
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SCRIPT_DIR"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║       A2A Demos Setup - Dependencies                       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check Python version (require 3.11+)
PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 11 ]); then
    echo "❌ Python 3.11+ required (found $PYTHON_VERSION)"
    exit 1
fi

echo "✓ Python $PYTHON_VERSION detected"
if [ "$PYTHON_MINOR" -ge 14 ]; then
    echo "  ⚠️  Note: Python 3.14+ may show Pydantic V1 deprecation warnings (safe to ignore)"
fi
echo ""

# Install shared module first
echo "📦 Installing shared module..."
cd "$SCRIPT_DIR/shared"
pip install -e . -q

# Setup Python environments for each agent
echo ""
echo "🐍 Setting up Python environments..."

for agent_dir in langchain-agent crewai-agent langgraph-agent; do
    echo "   Setting up $agent_dir..."
    cd "$SCRIPT_DIR/agents/$agent_dir"
    
    if [ ! -d ".venv" ]; then
        python -m venv .venv
    fi
    
    source .venv/bin/activate
    pip install -q --upgrade pip
    pip install -q -r requirements.txt
    pip install -q -e ../../shared
    deactivate
    
    echo "   ✓ $agent_dir ready"
done

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "   1. Copy .env.example to .env and add your credentials:"
echo "      - OPENAI_API_KEY (required)"
echo "      - CAPISCIO_API_KEY (from app.capisc.io → Settings → API Keys)"
echo ""
echo "   2. Run agents:  ./scripts/run-agents.sh"
echo ""
echo "   3. Run demo:    python scripts/demo_driver.py"
echo ""
echo "   4. Watch events: https://app.capisc.io/events"
echo "═══════════════════════════════════════════════════════════════"
