#!/usr/bin/env bash
#
# Setup all agent environments
#
# Usage:
#   ./scripts/setup.sh           # Install from PyPI (released versions)
#   ./scripts/setup.sh --local   # Install from local repos (pre-release testing)
#
# Note: Keys are auto-generated by the SDK when agents start
#
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$SCRIPT_DIR"

# Parse flags
USE_LOCAL=false
for arg in "$@"; do
    case $arg in
        --local) USE_LOCAL=true ;;
        --help|-h)
            echo "Usage: ./scripts/setup.sh [--local]"
            echo ""
            echo "  --local    Install CapiscIO packages from local sibling repos"
            echo "             (../capiscio-sdk-python, ../capiscio-mcp-python, ../langchain-capiscio)"
            echo "             instead of PyPI. Use for pre-release testing."
            exit 0
            ;;
    esac
done

echo "╔════════════════════════════════════════════════════════════╗"
if [ "$USE_LOCAL" = true ]; then
echo "║       A2A Demos Setup - LOCAL REPOS (dev mode)             ║"
else
echo "║       A2A Demos Setup - PyPI (release mode)                ║"
fi
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check Python version (require 3.11+)
PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 11 ]); then
    echo "❌ Python 3.11+ required (found $PYTHON_VERSION)"
    exit 1
fi

echo "✓ Python $PYTHON_VERSION detected"
if [ "$PYTHON_MINOR" -ge 14 ]; then
    echo "  ⚠️  Note: Python 3.14+ may show Pydantic V1 deprecation warnings (safe to ignore)"
fi
echo ""

# Verify local repos if --local
if [ "$USE_LOCAL" = true ]; then
    echo "🔍 Verifying local repos..."
    for repo in capiscio-sdk-python capiscio-mcp-python langchain-capiscio; do
        if [ ! -f "$SCRIPT_DIR/../$repo/pyproject.toml" ]; then
            echo "❌ Local repo not found: $SCRIPT_DIR/../$repo"
            echo "   Ensure all CapiscIO repos are cloned as siblings of a2a-demos."
            exit 1
        fi
        ver=$(grep '^version' "$SCRIPT_DIR/../$repo/pyproject.toml" | head -1 | cut -d'"' -f2)
        echo "   ✓ $repo ($ver)"
    done
    echo ""
fi

# Install shared module first
echo "📦 Installing shared module..."
cd "$SCRIPT_DIR/shared"
pip install -e . -q

# Setup Python environments for each agent
echo ""
echo "🐍 Setting up Python environments..."

for agent_dir in langchain-agent crewai-agent langgraph-agent; do
    echo "   Setting up $agent_dir..."
    cd "$SCRIPT_DIR/agents/$agent_dir"
    
    if [ ! -d ".venv" ]; then
        python3 -m venv .venv
    fi
    
    source .venv/bin/activate
    pip install -q --upgrade pip

    if [ "$USE_LOCAL" = true ]; then
        # Install local CapiscIO packages first (editable)
        pip install -q -e "$SCRIPT_DIR/../capiscio-sdk-python"
        pip install -q -e "$SCRIPT_DIR/../capiscio-mcp-python[mcp]"
        pip install -q -e "$SCRIPT_DIR/../langchain-capiscio"
        # Install remaining deps (frameworks, etc.) but skip capiscio packages
        pip install -q -r requirements.txt 2>/dev/null || true
    else
        pip install -q -r requirements.txt
    fi

    pip install -q -e ../../shared
    deactivate
    
    echo "   ✓ $agent_dir ready"
done

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ Setup complete!"
if [ "$USE_LOCAL" = true ]; then
echo ""
echo "   MODE: LOCAL REPOS (editable installs)"
echo "   Changes to capiscio-sdk-python, capiscio-mcp-python,"
echo "   and langchain-capiscio take effect immediately."
fi
echo ""
echo "Next steps:"
echo "   1. Copy .env.example to .env and add your credentials:"
echo "      - OPENAI_API_KEY (required)"
echo "      - CAPISCIO_API_KEY (from app.capisc.io → Settings → API Keys)"
echo ""
echo "   2. Run agents:  ./scripts/run-agents.sh"
echo ""
echo "   3. Run demo:    python scripts/demo_driver.py"
echo ""
echo "   4. Watch events: https://app.capisc.io/events"
echo "═══════════════════════════════════════════════════════════════"
